In [ ]:
import os
import sys

sys.path.append(os.path.dirname(os.getcwd()))
import dir_path
import pandas as pd

In [ ]:
df = pd.read_csv(dir_path.path.data_dir + '/12_19_교통사고정보.csv',encoding='utf-8')

In [ ]:
df

In [ ]:
df

In [ ]:
# 글자 변환


# 미리정의 


from enum import Enum


class transform(Enum):
    child = '어린이사고'
    bicycle = '자전거사고'
    dawn = '야간사고'
    old = '노인사고'
    pedestrian = '보행자사고'
    ##################
    code = '법정동코드'
    cases = '사고건수'
    cases_ratio = '사고건수 구성비'
    die = '사망자수'
    dieratio = '사망자수 구성비'
    fatality = '치사율'
    lnjured = '부상자수'
    lnjuredratio = '부상자수 구성비'

In [ ]:
transform.bicycle.value

In [9]:
import ENUM
import pandas as pd
import os
import sys
sys.path.append(os.path.dirname(os.getcwd()))#ipynb용
import dir_path

In [16]:
#메인테스트 메소드

def main(kind :str , year : int, doc :str):
    
    df = pd.read_csv(dir_path.path.data_dir + '/12_19_교통사고정보.csv',encoding='utf-8')
    trans = list(ENUM.transform)


    kind_list = df['대상사고 구분명'] == ENUM.transform[kind].value
    year_list = df['연도'] == year
    doc = ENUM.transform[doc].value
    return df[kind_list & year_list][doc].to_dict()

In [17]:
main('pedestrian',2012,'die')

{2: 9,
 7: 8,
 12: 6,
 17: 4,
 22: 10,
 27: 8,
 32: 10,
 37: 13,
 42: 4,
 47: 12,
 52: 14,
 57: 10,
 62: 19,
 67: 7,
 72: 11,
 77: 15,
 82: 10,
 87: 6,
 92: 13,
 97: 8,
 102: 9,
 107: 10,
 112: 8,
 117: 5,
 122: 13,
 127: 3,
 132: 2,
 137: 5,
 142: 4,
 147: 17,
 152: 5,
 157: 12,
 162: 8,
 167: 9,
 172: 7,
 177: 7,
 182: 9,
 187: 5,
 192: 3,
 197: 15,
 202: 3,
 207: 36,
 212: 22,
 217: 17,
 222: 17,
 227: 13,
 232: 15,
 237: 24,
 242: 10,
 247: 3,
 252: 9,
 257: 7,
 262: 23,
 267: 16,
 272: 13,
 277: 27,
 282: 6,
 287: 3,
 292: 11,
 297: 4,
 302: 5,
 307: 10,
 312: 27,
 317: 15,
 322: 17,
 327: 4,
 332: 1,
 337: 5,
 342: 21,
 347: 4,
 352: 3,
 357: 4,
 362: 8,
 367: 23,
 372: 2,
 377: 13,
 382: 0,
 387: 3,
 392: 3,
 397: 5,
 402: 4,
 407: 3,
 412: 1,
 417: 2,
 422: 3,
 427: 0,
 432: 2,
 437: 5,
 441: 2,
 446: 2,
 451: 23,
 456: 14,
 461: 8,
 466: 13,
 471: 4,
 476: 4,
 481: 4,
 486: 5,
 491: 4,
 496: 9,
 501: 2,
 506: 0,
 511: 28,
 516: 18,
 521: 8,
 526: 5,
 531: 15,
 536: 3,
 541: 11,
 546: 0,
 551: 7,
 556: 5,
 561: 5,
 566: 2,
 571: 8,
 576: 3,
 581: 17,
 586: 2,
 590: 36,
 595: 12,
 600: 10,
 605: 10,
 610: 7,
 615: 15,
 620: 2,
 625: 0,
 629: 1,
 634: 2,
 639: 4,
 644: 9,
 649: 6,
 654: 16,
 659: 13,
 664: 29,
 669: 14,
 674: 15,
 679: 6,
 684: 5,
 689: 4,
 694: 3,
 699: 4,
 704: 5,
 709: 4,
 714: 3,
 719: 4,
 724: 8,
 729: 7,
 734: 4,
 739: 3,
 744: 5,
 749: 5,
 754: 5,
 759: 5,
 764: 3,
 769: 28,
 774: 26,
 779: 6,
 784: 11,
 789: 14,
 794: 4,
 799: 6,
 804: 5,
 809: 6,
 814: 6,
 819: 7,
 824: 5,
 829: 0,
 834: 2,
 839: 2,
 844: 4,
 849: 4,
 854: 7,
 859: 3,
 864: 0,
 869: 3,
 873: 0,
 877: 12,
 882: 24,
 887: 3,
 892: 20,
 897: 12,
 902: 6,
 907: 1,
 912: 2,
 917: 3,
 922: 12,
 927: 6,
 932: 5,
 937: 4,
 942: 5,
 947: 3,
 952: 3,
 957: 4,
 962: 3,
 967: 40,
 972: 22,
 977: 14,
 982: 6,
 987: 9,
 992: 12,
 997: 4,
 1002: 8,
 1007: 21,
 1012: 12,
 1017: 7,
 1022: 8,
 1027: 1,
 1032: 15,
 1037: 13,
 1042: 15,
 1047: 13,
 1052: 7,
 1057: 8,
 1062: 7,
 1067: 1,
 1072: 2,
 1077: 15,
 1082: 18,
 1087: 11,
 1092: 14,
 1097: 20,
 1102: 8,
 1107: 15,
 1112: 11,
 1117: 8,
 1122: 12,
 1127: 10,
 1132: 3,
 1137: 8,
 1142: 11,
 1147: 1}

In [ ]:
 '어린이사고'
list_2018 = df['연도'] == 2018 
# 반환 예정값
print(df[child_list & list_2018]['법정동코드'].to_dict())

In [ ]:
acc 
for i in acc_list:

In [ ]:
df